project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_ex/Hands-on_Ex01/Hands-on_Ex04.html"
          - text: "Hands-on Exercise 5 - Corrgram"
            href: "Hands-on_ex/Hands-on_Ex05/Hands-on_Ex05-Corrgram.html"
          - text: "Hands-on Exercise 5 - Ternary"
            href: "Hands-on_ex/Hands-on_Ex05/Hands-on_Ex05-Ternary.html"
          - text: "Hands-on Exercise 5 - Parallel"
            href: "Hands-on_ex/Hands-on_Ex05/Hands-on_Ex05-Parallel.html"
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-Home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-Home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3"
            href: "Take-home_Ex/Take-Home_Ex03/Take-home_Ex03.html"
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise 5 - Corrgram"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05-Corrgram.html"
          - text: "In-class Exercise 5 - Ternary"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05-Ternary.html"
          - text: "In-class Exercise 5 - Parallel"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05-Parallel.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

